# Generated by Django 4.2.26 on 2025-11-06 02:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('OF', 'Outfield'), ('DH', 'Designated Hitter')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_player_name_8cd894_idx'), models.Index(fields=['position'], name='api_player_positio_636a9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('at_bats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('runs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('doubles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('triples', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('home_runs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rbis', models.IntegerField(help_text='Runs Batted In', validators=[django.core.validators.MinValueValidator(0)])),
                ('walks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('strikeouts', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stolen_bases', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('caught_stealing', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('batting_avg', models.DecimalField(decimal_places=3, help_text='Batting Average', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('on_base_pct', models.DecimalField(decimal_places=3, help_text='On-Base Percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('slugging_pct', models.DecimalField(decimal_places=3, help_text='Slugging Percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('ops', models.DecimalField(decimal_places=3, help_text='On-Base Plus Slugging', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_stats', to='api.player')),
            ],
            options={
                'verbose_name': 'Career Stats',
                'verbose_name_plural': 'Career Stats',
                'indexes': [models.Index(fields=['-home_runs'], name='api_careers_home_ru_e75e25_idx'), models.Index(fields=['-batting_avg'], name='api_careers_batting_56c1d4_idx'), models.Index(fields=['-ops'], name='api_careers_ops_cb0fc3_idx')],
            },
        ),
    ]
